version: '3.4'

services:
  db:
    image: mysql:5.7
    volumes:
      - ./bike-rental.db/bikerentaldb.sql:/docker-entrypoint-initdb.d/bikerentaldb.sql
      - dbdata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: temporary_db_pass
    secrets:
      - db_root_password
    networks:
      - mynetwork

  backend:
    build: 
      context: ./bike-rental.backend/
      dockerfile: BikeRental.Api/Dockerfile
    depends_on:
      - db
    networks:
      - mynetwork
    ports:
      - "5094:5094"
      - "7052:7052"

  frontend:
    build: 
      context: ./bike-rental.frontend.test/
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - mynetwork
    ports:
      - "5015:5015"
      - "7127:7127"
      - "8008:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

volumes:
  dbdata:

networks:
  mynetwork:
    name: mynetwork

secrets:
  db_root_password:
    file: ./secrets/dbdata/root_password