version: '3'

services:
  db:
    image: mysql
    container_name: mydatabase
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE_FILE: /run/secrets/db_database
    volumes:
      - ./bikerentaldb.sql:/docker-entrypoint-initdb.d/bikerentaldb.sql
    secrets:
      - db_root_password
      - db_database
    networks:
      - mynetwork

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /var/lib/mysql #placeholder for the actual path to the database

networks:
  mynetwork:
    name: mynetwork

secrets:
  db_root_password:
    file: secrets/dbdata/root_password
  db_database:
    file: secrets/dbdata/database