version: '3.4'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "BikeRental!1"
      MSSQL_PID: Express
    ports:
      - "1433:1433"
  backend-api:
    environment:
      ASPNETCORE_HTTP_PORT: "https://+:8081"
      ASPNETCORE_URLS: "http://+8080"
    build: .
    ports:
      - "8080:80"