version: '3.4'

networks:
  dev:
    driver: bridge

services:
  backend-api:
    image: docker.io/library/backendapi
    depends_on:
      - "app_db"
    container_name: backendapi-services
    ports:
      - "8088:80"
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=PORTABLEHUB\\SQLEXPRESS;Database=BikeRental;Trusted_Connection=True;TrustServerCertificate=true
      - ASPNETCORE_URLS=http://+:80
      networks:
        - dev
    
    app_db:
      image: mysql:latest
      container_name: app_db
      environment:
      