# Use the official .NET SDK image as the base image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-new

# Set the working directory to /app
WORKDIR /appfrontend

# Copy the solution file and restore dependencies
COPY BikeRental.Frontend.sln .
COPY bike-rental.frontend/bike-rental.frontend.test.csproj ./bike-rental.frontend/
COPY bike-rental.frontend/bike-rental.frontend.test.csproj.user ./bike-rental.frontend/

# Restore NuGet packages
RUN dotnet restore

# Copy the rest of the application code
COPY bike-rental.frontend/. ./bike-rental.frontend/

# Build the application
RUN dotnet build -c Release -o out

# Create the runtime image
FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-final
WORKDIR WORKDIR /appfrontend
COPY --from=build-new /appfrontend/out .

# Expose port 80 for the application
EXPOSE 80

# Specify the entry point for the application
ENTRYPOINT ["dotnet", "bike-rental.frontend.test.dll"]